### ISSUE TITLE
Having an issue running this: Seg Fault

### ISSUE THREAD

**Issue by MostHated** [lucasluitjes/midityper-fcb1010#1]
Hey there, 
This package/lib is exactly what I was looking for, as I have had a FCB1010 sitting in my garage for the better part of a decade, and I was a midi to USB adapter on amazon and figured there must be some way to make something work. Low and behold, I see this repo, so I was excited to give it a go. Unfortunately, I was promptly greeted by a segault. I have not worked with Ruby much, so I figured I would see if you made any headway with this issue, as it looks like you ran into a similar issue back in 2018 (https://github.com/arirusso/alsa-rawmidi/issues/7)? 

The only thing is that it looks like I am using a different midi to USB adapter. Mine shows up as the last one in this list:

<details>
<summary>/proc/asound</summary>

```sh
zsh ❯ cat /proc/asound/cards
 0 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xef120000 irq 194
 1 [Generic_1      ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xeef88000 irq 196
 2 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xeef80000 irq 197
 3 [S              ]: USB-Audio - Loupedeck Live S
                      Loupedeck Loupedeck Live S at usb-0000:59:00.4-1.3, high speed
 4 [Audio          ]: USB-Audio - USB Audio
                      Generic USB Audio at usb-0000:56:00.0-8, high speed
 5 [CH345          ]: USB-Audio - CH345
                      QinHeng CH345 at usb-0000:59:00.4-1.1.4, full speed

```

</details>

but in ` /proc/asound/devices/` I see raw midi (seen below), which seemed to be mentioned as necessary in that issue post, so I am guessing it might be ok, but this is my first time ever dealing with midi on the PC side of things, so I honestly have no idea.

```sh
  2: [ 3- 0]: raw midi
...
 26: [ 5- 0]: raw midi
```

I would love to get this working, so if I need to get a different device, ex. the same one you have that is known working, that is fine with me, I just am not sure how to know. 

That said, in your code, I attempted to change out your dmesg grep from USBMIDI to just MIDI, as no messages in my dmesg output has that string, but using just MIDI gives  return of:

```sh
zsh ❯ _ dmesg|grep "MIDI"|tail -n1
[116658.250910] usb 9-1.1.4: SerialNumber: USB MIDI Interface
```
I am not quite sure if this is the expected return value, though, which the main.rb file is expecting and can use. 

If you happen to have any insight into this that you might be able to share, that would be greatly appreciated.
Thanks,
-MH

**Comment by lucasluitjes** [comment]
Hi! 

If you change https://github.com/lucasluitjes/midityper-fcb1010/blob/main/main.rb#L22 from  `@input = UniMIDI::Input.use(:first)` to  `@input = UniMIDI::Input.gets` you should be able to interactively select the device. Let me know if that works and I'll make device selection configurable.

If that doesn't solve it, can you let me know which OS and version you're using and the output of when you try to run it and it segfaults?

**Comment by MostHated** [comment]
I appreciate the reply. I made the requested change, but unfortunately it still seg faulted. Below is the output from the attempt:

https://gist.github.com/MostHated/534c2151a967c6c2ce3721fc8895ab8c

<details>
<summary>System Details</summary>

```sh
OS: Pop!_OS 22.04 LTS x86_64
Host: X670E Taichi
Kernel: 6.0.12-76060006-generic
Uptime: 2 days, 5 hours, 52 mins
Packages: 4481 (dpkg), 43 (nix-default), 115 (flatpak), 15 (snap)
Shell: zsh 5.8.1
Resolution: 2560x1080
DE: GNOME 42.3.1
WM: Mutter
WM Theme: Pop-dark
Theme: Pop-dark [GTK2/3]
Icons: Flatery-Orange-Dark [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 7950X (32) @ 5.881GHz
GPU: AMD ATI Radeon RX 6900 XT
GPU: AMD ATI 59:00.0 Device 164e
Memory: 31323MiB / 63415MiB
```

</details>

Please do let me know if any additional details are needed
Thanks, 
-MH

**Comment by lucasluitjes** [comment]
I think this is an issue in the alsa-rawmidi gem. Can you try putting the following in a ruby script and running it?

```
require 'alsa-rawmidi'
puts AlsaRawMIDI::Device.all.to_s
AlsaRawMIDI::Input.first.open {|input| puts input.gets }
```

If that also crashes, the next step would be to report it here: https://github.com/arirusso/alsa-rawmidi/issues
